<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AutomezziSeeder extends Seeder
{
    public function run()
    {
        // idAssociazione = 5, idAnno = 2024 per tutti i record
        DB::table('automezzi')->insert([
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 1',
                'Targa'                             => 'DR 585 TM',
                'CodiceIdentificativo'              => 'B23',
                'AnnoPrimaImmatricolazione'         => 2009,
                // 'AnnoAcquisto'                   => null,   // rimosso
                'Modello'                           => 'FIAT DUCATO',
                'TipoVeicolo'                       => 'MEZZO DISABILI',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 321247,
                'TipoCarburante'                    => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 2',
                'Targa'                             => 'CT 163 LM',
                'CodiceIdentificativo'              => 'B25',
                'AnnoPrimaImmatricolazione'         => 2014,
                // 'AnnoAcquisto'                   => null,
                'Modello'                           => 'FIAT FIORINO',
                'TipoVeicolo'                       => 'AUTOVETTURA',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 54944,
                'TipoCarburante'                    => 'GPL',
                'DataUltimaAutorizzazioneSanitaria' => '2023-03-26',
                'DataUltimoCollaudo'                => '2023-08-16',
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 3',
                'Targa'                             => 'DI 071 HC',
                'CodiceIdentificativo'              => 'D11',
                'AnnoPrimaImmatricolazione'         => 2009,
                // 'AnnoAcquisto'                   => 2021,
                'Modello'                           => 'FIAT SCUDO',
                'TipoVeicolo'                       => 'AMBULANZA TRAUMA',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 269373,
                'TipoCarburante'                    => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => '2023-01-24',
                'DataUltimoCollaudo'                => '2023-04-19',
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 4',
                'Targa'                             => 'DB 638 TT',
                'CodiceIdentificativo'              => 'D26',
                'AnnoPrimaImmatricolazione'         => 2008,
                // 'AnnoAcquisto'                   => 2010,
                'Modello'                           => 'FIAT FIORINO',
                'TipoVeicolo'                       => 'AUTOVETTURA',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 164276,
                'TipoCarburante'                    => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => '2023-05-17',
                'DataUltimoCollaudo'                => '2023-07-03',
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 5',
                'Targa'                             => 'DT 887 TE',
                'CodiceIdentificativo'              => 'D29',
                'AnnoPrimaImmatricolazione'         => 2007,
                // 'AnnoAcquisto'                   => null,
                'Modello'                           => 'FIAT SCUDO',
                'TipoVeicolo'                       => 'AMBULANZA TRAUMA',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 343135,
                'TipoCarburante'                    => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => '2023-02-09',
                'DataUltimoCollaudo'                => '2023-04-20',
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 6',
                'Targa'                             => 'EB 540 RJ',
                'CodiceIdentificativo'              => 'D38',
                'AnnoPrimaImmatricolazione'         => 2007,
                // 'AnnoAcquisto'                   => null,
                'Modello'                           => 'FIAT FIORINO',
                'TipoVeicolo'                       => 'AUTOVETTURA',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 248180,
                'TipoCarburante'                    => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => '2023-03-17',
                'DataUltimoCollaudo'                => '2023-04-25',
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 7',
                'Targa'                             => 'EH 072 RA',
                'CodiceIdentificativo'              => 'B12',
                'AnnoPrimaImmatricolazione'         => 2010,
                // 'AnnoAcquisto'                   => null,
                'Modello'                           => 'FIAT DAILY',
                'TipoVeicolo'                       => 'MEZZO DISABILI',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 261471,
                'TipoCarburante'                    => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => '2023-05-15',
                'DataUltimoCollaudo'                => '2023-06-21',
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 8',
                'Targa'                             => 'EM 429 TS',
                'CodiceIdentificativo'              => 'B18',
                'AnnoPrimaImmatricolazione'         => 2010,
                // 'AnnoAcquisto'                   => null,
                'Modello'                           => 'FIAT PUNTO',
                'TipoVeicolo'                       => 'AUTOVETTURA',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 149896,
                'TipoCarburante'                    => 'B/G',
                'DataUltimaAutorizzazioneSanitaria' => '2023-03-15',
                'DataUltimoCollaudo'                => '2023-05-15',
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 9',
                'Targa'                             => 'EP 911 RL',
                'CodiceIdentificativo'              => 'B20',
                'AnnoPrimaImmatricolazione'         => 2007,
                // 'AnnoAcquisto'                   => null,
                'Modello'                           => 'FIAT DUCATO',
                'TipoVeicolo'                       => 'MEZZO DISABILI',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 367305,
                'TipoCarburante'                    => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 10',
                'Targa'                             => 'HP 378 RA',
                'CodiceIdentificativo'              => 'B21',
                'AnnoPrimaImmatricolazione'         => 2009,
                // 'AnnoAcquisto'                   => null,
                'Modello'                           => 'PEUGEOT PARTNER',
                'TipoVeicolo'                       => 'AUTOVETTURA',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 235950,
                'TipoCarburante'                    => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => '2023-02-15',
                'DataUltimoCollaudo'                => '2023-04-15',
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 11',
                'Targa'                             => 'TR 028 GL',
                'CodiceIdentificativo'              => 'D42',
                'AnnoPrimaImmatricolazione'         => null,
                // 'AnnoAcquisto'                   => null,
                'Modello'                           => 'DISMESSE',
                'TipoVeicolo'                       => 'DISMESSE',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 0,
                'TipoCarburante'                    => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 12',
                'Targa'                             => 'DR 574 XX',
                'CodiceIdentificativo'              => 'A53',
                'AnnoPrimaImmatricolazione'         => 2023,
                // 'AnnoAcquisto'                   => null,
                'Modello'                           => 'FIAT DOBLO',
                'TipoVeicolo'                       => 'AUTOVETTURA',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 0,
                'TipoCarburante'                    => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 13',
                'Targa'                             => 'DR 677 LL',
                'CodiceIdentificativo'              => 'A59',
                'AnnoPrimaImmatricolazione'         => 2024,
                // 'AnnoAcquisto'                   => null,
                'Modello'                           => 'FIAT PANDA',
                'TipoVeicolo'                       => 'AUTOVETTURA',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 0,
                'TipoCarburante'                    => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 14',
                'Targa'                             => 'DT 887 TF',
                'CodiceIdentificativo'              => 'A60',
                'AnnoPrimaImmatricolazione'         => 2010,
                // 'AnnoAcquisto'                   => null,
                'Modello'                           => 'FIAT SCUDO',
                'TipoVeicolo'                       => 'MEZZO DISABILI',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 0,
                'TipoCarburante'                    => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 15',
                'Targa'                             => 'EA 768 KC',
                'CodiceIdentificativo'              => 'A62',
                'AnnoPrimaImmatricolazione'         => 2007,
                // 'AnnoAcquisto'                   => null,
                'Modello'                           => 'FIAT PUNTO',
                'TipoVeicolo'                       => 'AUTOVETTURA',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 0,
                'TipoCarburante'                    => 'B/G',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 16',
                'Targa'                             => 'EP 911 RB',
                'CodiceIdentificativo'              => 'A64',
                'AnnoPrimaImmatricolazione'         => 2008,
                // 'AnnoAcquisto'                   => null,
                'Modello'                           => 'FIAT DUCATO',
                'TipoVeicolo'                       => 'MEZZO DISABILI',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 0,
                'TipoCarburante'                    => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 17',
                'Targa'                             => 'FJ 656 TS',
                'CodiceIdentificativo'              => 'A65',
                'AnnoPrimaImmatricolazione'         => 2009,
                // 'AnnoAcquisto'                   => null,
                'Modello'                           => 'PEUGEOT PARTNER',
                'TipoVeicolo'                       => 'AUTOVETTURA',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 0,
                'TipoCarburante'                    => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 18',
                'Targa'                             => 'FJ 657 TS',
                'CodiceIdentificativo'              => 'A69',
                'AnnoPrimaImmatricolazione'         => 2010,
                // 'AnnoAcquisto'                   => null,
                'Modello'                           => 'FIAT FIORINO',
                'TipoVeicolo'                       => 'AUTOVETTURA',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 0,
                'TipoCarburante'                    => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 19',
                'Targa'                             => 'FK 031 SK',
                'CodiceIdentificativo'              => 'B29',
                'AnnoPrimaImmatricolazione'         => 2007,
                // 'AnnoAcquisto'                   => null,
                'Modello'                           => 'FIAT SCUDO',
                'TipoVeicolo'                       => 'MEZZO DISABILI',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 0,
                'TipoCarburante'                    => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 20',
                'Targa'                             => 'FK 031 SJ',
                'CodiceIdentificativo'              => 'B30',
                'AnnoPrimaImmatricolazione'         => 2009,
                // 'AnnoAcquisto'                   => null,
                'Modello'                           => 'FIAT FIORINO',
                'TipoVeicolo'                       => 'AUTOVETTURA',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 0,
                'TipoCarburante'                    => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 21',
                'Targa'                             => 'GK 241 JD',
                'CodiceIdentificativo'              => 'B40',
                'AnnoPrimaImmatricolazione'         => 2006,
                // 'AnnoAcquisto'                   => null,
                'Modello'                           => 'FIAT DUCATO',
                'TipoVeicolo'                       => 'MEZZO DISABILI',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 0,
                'TipoCarburante'                    => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 22',
                'Targa'                             => 'GK 241 JD',
                'CodiceIdentificativo'              => 'B50',
                'AnnoPrimaImmatricolazione'         => 2006,
                // 'AnnoAcquisto'                   => null,
                'Modello'                           => 'FIAT FIORINO',
                'TipoVeicolo'                       => 'AUTOVETTURA',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 0,
                'TipoCarburante'                    => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 23',
                'Targa'                             => 'DY 684 DK',
                'CodiceIdentificativo'              => 'B61',
                'AnnoPrimaImmatricolazione'         => 2009,
              //  'AnnoAcquisto'                      => null, // rimane commented se in futuro lo aggiungi
                'Modello'                           => 'FIAT SCUDO',
                'TipoVeicolo'                       => 'MEZZO DISABILI',
               // 'KmRiferimento'                     => 0,
                'KmTotali'                          => 0,
                'TipoCarburante'                    => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
                'created_at'                        => now(),
                'updated_at'                        => now(),
            ],
        ]);
    }
}
