<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AutomezziSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();

        $rows = [
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 1',
                'Targa'                             => 'DR 585 TM',
                'CodiceIdentificativo'              => 'B23',
                'AnnoPrimaImmatricolazione'         => 2009,
                'Modello'                           => 'FIAT DUCATO',
                'TipoVeicoloNome'                   => 'MEZZO DISABILI',
                'KmTotali'                          => 321247,
                'TipoCarburanteNome'                => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 2',
                'Targa'                             => 'CT 163 LM',
                'CodiceIdentificativo'              => 'B25',
                'AnnoPrimaImmatricolazione'         => 2014,
                'Modello'                           => 'FIAT FIORINO',
                'TipoVeicoloNome'                   => 'AUTOVETTURA',
                'KmTotali'                          => 54944,
                'TipoCarburanteNome'                => 'GPL',
                'DataUltimaAutorizzazioneSanitaria' => '2023-03-26',
                'DataUltimoCollaudo'                => '2023-08-16',
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 3',
                'Targa'                             => 'DI 071 HC',
                'CodiceIdentificativo'              => 'D11',
                'AnnoPrimaImmatricolazione'         => 2009,
                'Modello'                           => 'FIAT SCUDO',
                'TipoVeicoloNome'                   => 'AMBULANZA TRAUMA',
                'KmTotali'                          => 269373,
                'TipoCarburanteNome'                => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => '2023-01-24',
                'DataUltimoCollaudo'                => '2023-04-19',
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 4',
                'Targa'                             => 'DB 638 TT',
                'CodiceIdentificativo'              => 'D26',
                'AnnoPrimaImmatricolazione'         => 2008,
                'Modello'                           => 'FIAT FIORINO',
                'TipoVeicoloNome'                   => 'AUTOVETTURA',
                'KmTotali'                          => 164276,
                'TipoCarburanteNome'                => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => '2023-05-17',
                'DataUltimoCollaudo'                => '2023-07-03',
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 5',
                'Targa'                             => 'DT 887 TE',
                'CodiceIdentificativo'              => 'D29',
                'AnnoPrimaImmatricolazione'         => 2007,
                'Modello'                           => 'FIAT SCUDO',
                'TipoVeicoloNome'                   => 'AMBULANZA TRAUMA',
                'KmTotali'                          => 343135,
                'TipoCarburanteNome'                => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => '2023-02-09',
                'DataUltimoCollaudo'                => '2023-04-20',
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 6',
                'Targa'                             => 'EB 540 RJ',
                'CodiceIdentificativo'              => 'D38',
                'AnnoPrimaImmatricolazione'         => 2007,
                'Modello'                           => 'FIAT FIORINO',
                'TipoVeicoloNome'                   => 'AUTOVETTURA',
                'KmTotali'                          => 248180,
                'TipoCarburanteNome'                => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => '2023-03-17',
                'DataUltimoCollaudo'                => '2023-04-25',
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 7',
                'Targa'                             => 'EH 072 RA',
                'CodiceIdentificativo'              => 'B12',
                'AnnoPrimaImmatricolazione'         => 2010,
                'Modello'                           => 'FIAT DAILY',
                'TipoVeicoloNome'                   => 'MEZZO DISABILI',
                'KmTotali'                          => 261471,
                'TipoCarburanteNome'                => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => '2023-05-15',
                'DataUltimoCollaudo'                => '2023-06-21',
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 8',
                'Targa'                             => 'EM 429 TS',
                'CodiceIdentificativo'              => 'B18',
                'AnnoPrimaImmatricolazione'         => 2010,
                'Modello'                           => 'FIAT PUNTO',
                'TipoVeicoloNome'                   => 'AUTOVETTURA',
                'KmTotali'                          => 149896,
                'TipoCarburanteNome'                => 'B/G',
                'DataUltimaAutorizzazioneSanitaria' => '2023-03-15',
                'DataUltimoCollaudo'                => '2023-05-15',
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 9',
                'Targa'                             => 'EP 911 RL',
                'CodiceIdentificativo'              => 'B20',
                'AnnoPrimaImmatricolazione'         => 2007,
                'Modello'                           => 'FIAT DUCATO',
                'TipoVeicoloNome'                   => 'MEZZO DISABILI',
                'KmTotali'                          => 367305,
                'TipoCarburanteNome'                => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 10',
                'Targa'                             => 'HP 378 RA',
                'CodiceIdentificativo'              => 'B21',
                'AnnoPrimaImmatricolazione'         => 2009,
                'Modello'                           => 'PEUGEOT PARTNER',
                'TipoVeicoloNome'                   => 'AUTOVETTURA',
                'KmTotali'                          => 235950,
                'TipoCarburanteNome'                => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => '2023-02-15',
                'DataUltimoCollaudo'                => '2023-04-15',
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 11',
                'Targa'                             => 'TR 028 GL',
                'CodiceIdentificativo'              => 'D42',
                'AnnoPrimaImmatricolazione'         => null,
                'Modello'                           => 'DISMESSE',
                'TipoVeicoloNome'                   => 'DISMESSE',
                'KmTotali'                          => 0,
                'TipoCarburanteNome'                => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 12',
                'Targa'                             => 'DR 574 XX',
                'CodiceIdentificativo'              => 'A53',
                'AnnoPrimaImmatricolazione'         => 2023,
                'Modello'                           => 'FIAT DOBLO',
                'TipoVeicoloNome'                   => 'AUTOVETTURA',
                'KmTotali'                          => 0,
                'TipoCarburanteNome'                => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 13',
                'Targa'                             => 'DR 677 LL',
                'CodiceIdentificativo'              => 'A59',
                'AnnoPrimaImmatricolazione'         => 2024,
                'Modello'                           => 'FIAT PANDA',
                'TipoVeicoloNome'                   => 'AUTOVETTURA',
                'KmTotali'                          => 0,
                'TipoCarburanteNome'                => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 14',
                'Targa'                             => 'DT 887 TF',
                'CodiceIdentificativo'              => 'A60',
                'AnnoPrimaImmatricolazione'         => 2010,
                'Modello'                           => 'FIAT SCUDO',
                'TipoVeicoloNome'                   => 'MEZZO DISABILI',
                'KmTotali'                          => 0,
                'TipoCarburanteNome'                => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 15',
                'Targa'                             => 'EA 768 KC',
                'CodiceIdentificativo'              => 'A62',
                'AnnoPrimaImmatricolazione'         => 2007,
                'Modello'                           => 'FIAT PUNTO',
                'TipoVeicoloNome'                   => 'AUTOVETTURA',
                'KmTotali'                          => 0,
                'TipoCarburanteNome'                => 'B/G',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 16',
                'Targa'                             => 'EP 911 RB',
                'CodiceIdentificativo'              => 'A64',
                'AnnoPrimaImmatricolazione'         => 2008,
                'Modello'                           => 'FIAT DUCATO',
                'TipoVeicoloNome'                   => 'MEZZO DISABILI',
                'KmTotali'                          => 0,
                'TipoCarburanteNome'                => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 17',
                'Targa'                             => 'FJ 656 TS',
                'CodiceIdentificativo'              => 'A65',
                'AnnoPrimaImmatricolazione'         => 2009,
                'Modello'                           => 'PEUGEOT PARTNER',
                'TipoVeicoloNome'                   => 'AUTOVETTURA',
                'KmTotali'                          => 0,
                'TipoCarburanteNome'                => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 18',
                'Targa'                             => 'FJ 657 TS',
                'CodiceIdentificativo'              => 'A69',
                'AnnoPrimaImmatricolazione'         => 2010,
                'Modello'                           => 'FIAT FIORINO',
                'TipoVeicoloNome'                   => 'AUTOVETTURA',
                'KmTotali'                          => 0,
                'TipoCarburanteNome'                => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 19',
                'Targa'                             => 'FK 031 SK',
                'CodiceIdentificativo'              => 'B29',
                'AnnoPrimaImmatricolazione'         => 2007,
                'Modello'                           => 'FIAT SCUDO',
                'TipoVeicoloNome'                   => 'MEZZO DISABILI',
                'KmTotali'                          => 0,
                'TipoCarburanteNome'                => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 20',
                'Targa'                             => 'FK 031 SJ',
                'CodiceIdentificativo'              => 'B30',
                'AnnoPrimaImmatricolazione'         => 2009,
                'Modello'                           => 'FIAT FIORINO',
                'TipoVeicoloNome'                   => 'AUTOVETTURA',
                'KmTotali'                          => 0,
                'TipoCarburanteNome'                => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 21',
                'Targa'                             => 'GK 241 JD',
                'CodiceIdentificativo'              => 'B40',
                'AnnoPrimaImmatricolazione'         => 2006,
                'Modello'                           => 'FIAT DUCATO',
                'TipoVeicoloNome'                   => 'MEZZO DISABILI',
                'KmTotali'                          => 0,
                'TipoCarburanteNome'                => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 22',
                'Targa'                             => 'GK 241 JD',
                'CodiceIdentificativo'              => 'B50',
                'AnnoPrimaImmatricolazione'         => 2006,
                'Modello'                           => 'FIAT FIORINO',
                'TipoVeicoloNome'                   => 'AUTOVETTURA',
                'KmTotali'                          => 0,
                'TipoCarburanteNome'                => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
            ],
            [
                'idAssociazione'                    => 5,
                'idAnno'                            => 2024,
                'Automezzo'                         => 'AUTO 23',
                'Targa'                             => 'DY 684 DK',
                'CodiceIdentificativo'              => 'B61',
                'AnnoPrimaImmatricolazione'         => 2009,
                'Modello'                           => 'FIAT SCUDO',
                'TipoVeicoloNome'                   => 'MEZZO DISABILI',
                'KmTotali'                          => 0,
                'TipoCarburanteNome'                => 'DIESEL',
                'DataUltimaAutorizzazioneSanitaria' => null,
                'DataUltimoCollaudo'                => null,
            ],
        ];

        foreach ($rows as $r) {
            // idTipoVeicolo
            $idTipoVeicolo = DB::table('vehicle_types')
                ->where('nome', $r['TipoVeicoloNome'])
                ->value('id');
            if (! $idTipoVeicolo) {
                $idTipoVeicolo = DB::table('vehicle_types')->insertGetId([
                    'nome'       => $r['TipoVeicoloNome'],
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
            }

            // idTipoCarburante
            $idTipoCarb = DB::table('fuel_types')
                ->where('nome', $r['TipoCarburanteNome'])
                ->value('id');
            if (! $idTipoCarb) {
                $idTipoCarb = DB::table('fuel_types')->insertGetId([
                    'nome'       => $r['TipoCarburanteNome'],
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
            }

            // insert automezzo
            DB::table('automezzi')->insert([
                'idAssociazione'                    => $r['idAssociazione'],
                'idAnno'                            => $r['idAnno'],
                'Automezzo'                         => $r['Automezzo'],
                'Targa'                             => $r['Targa'],
                'CodiceIdentificativo'              => $r['CodiceIdentificativo'],
                'AnnoPrimaImmatricolazione'         => $r['AnnoPrimaImmatricolazione'],
                'Modello'                           => $r['Modello'],
                'idTipoVeicolo'                     => $idTipoVeicolo,
                'KmTotali'                          => $r['KmTotali'],
                'idTipoCarburante'                  => $idTipoCarb,
                'DataUltimaAutorizzazioneSanitaria' => $r['DataUltimaAutorizzazioneSanitaria'],
                'DataUltimoCollaudo'                => $r['DataUltimoCollaudo'],
                'created_at'                        => $now,
                'updated_at'                        => $now,
            ]);
        }
    }
}
