-- DROP TABLE IF EXISTS `ter_nations`;

-- -- CREATE TABLE `ter_nations` (
--   `denominazione_continente` varchar(50) NOT NULL,
--   `denominazione_area` varchar(100) NOT NULL,
--   `codice_belfiore` varchar(4) NOT NULL,
--   `sigla_nazione` varchar(3) NOT NULL,
--   `denominazione_nazione` varchar(100) NOT NULL,
--   `denominazione_cittadinanza` varchar(100) NOT NULL,
--   `codice_iso_2` varchar(2) NOT NULL,
--   `codice_iso_3` varchar(3) NOT NULL,
--   `codice_istat` decimal(5,1),
--   `codice_min` decimal(5,1),
--   `codice_unsd_m49` varchar(5) NOT NULL,
--   `active` tinyint(1) NOT NULL,
--   PRIMARY KEY (`codice_belfiore`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- LOCK TABLES `ter_nations` WRITE;
INSERT INTO `ter_nations` (`denominazione_continente`, `denominazione_area`, `codice_belfiore`, `sigla_nazione`, `denominazione_nazione`, `denominazione_cittadinanza`, `codice_iso_2`, `codice_iso_3`, `codice_istat`, `codice_min`, `codice_unsd_m49`, `active`) VALUES
('Africa', 'Africa centro meridionale', 'Z302', 'ANG', 'Angola', 'Angolana', 'AO', 'AGO', 402, 402, '24', 1),
('Africa', 'Africa centro meridionale', 'Z358', 'BB', 'Botswana', 'Botswaniana', 'BW', 'BWA', 408, 408, '72', 1),
('Africa', 'Africa centro meridionale', 'Z306', 'CAM', 'Camerun', 'Camerunese', 'CM', 'CMR', 411, 411, '120', 1),
('Africa', 'Africa centro meridionale', 'Z309', 'TCH', 'Ciad', 'Ciadiana', 'TD', 'TCD', 415, 415, '148', 1),
('Africa', 'Africa centro meridionale', 'Z311', 'RCB', 'Congo', 'Congolese (repubblica popolare del congo)', 'CG', 'COG', 418, 418, '178', 1),
('Africa', 'Africa centro meridionale', 'Z349', 'SD', 'Eswatini', 'Swazi', 'SZ', 'SWZ', 456, 456, '748', 1),
('Africa', 'Africa centro meridionale', 'Z316', 'G', 'Gabon', 'Gabonese', 'GA', 'GAB', 421, 421, '266', 1),
('Africa', 'Africa centro meridionale', 'Z321', 'GQ', 'Guinea equatoriale', 'Equatoguineana', 'GQ', 'GNQ', 427, 427, '226', 1),
('Africa', 'Africa centro meridionale', 'Z359', 'LS', 'Lesotho', 'Lesothiana', 'LS', 'LSO', 429, 429, '426', 1),
('Africa', 'Africa centro meridionale', 'Z300', 'NAM', 'Namibia', 'Namibiana', NULL, 'NAM', 441, 441, '516', 1),
('Africa', 'Africa centro meridionale', 'Z308', 'RCA', 'Repubblica Centrafricana', 'Centraficana', 'CF', 'CAF', 414, 414, '140', 1),
('Africa', 'Africa centro meridionale', 'Z312', 'ZRE', 'Repubblica Democratica del Congo', 'Congolese (repubblica democratica del congo)', 'CD', 'COD', 463, 463, '180', 1),
('Africa', 'Africa centro meridionale', 'Z341', 'STP', 'Sao Tomé e Principe', 'Sao tome'' e principe', 'ST', 'STP', 448, 448, '678', 1),
('Africa', 'Africa centro meridionale', 'Z347', 'ZA', 'Sudafrica', 'Sudafricana', 'ZA', 'ZAF', 454, 454, '710', 1),
('Africa', 'Africa occidentale', 'Z314', 'BPB', 'Benin', 'Beninese', 'BJ', 'BEN', 406, 406, '204', 1),
('Africa', 'Africa occidentale', 'Z354', 'RHV', 'Burkina Faso', 'Burkinabè', 'BF', 'BFA', 409, 409, '854', 1),
('Africa', 'Africa occidentale', 'Z307', 'CV', 'Capo Verde', 'Capoverdiana', 'CV', 'CPV', 413, 413, '132', 1),
('Africa', 'Africa occidentale', 'Z313', 'CI', 'Costa d''Avorio', 'Ivoriana', 'CI', 'CIV', 404, 404, '384', 1),
('Africa', 'Africa occidentale', 'Z317', 'WAG', 'Gambia', 'Gambiana', 'GM', 'GMB', 422, 422, '270', 1),
('Africa', 'Africa occidentale', 'Z318', 'GH', 'Ghana', 'Ghanese', 'GH', 'GHA', 423, 423, '288', 1),
('Africa', 'Africa occidentale', 'Z319', 'RG', 'Guinea', 'Guineana (guinea)', 'GN', 'GIN', 425, 425, '324', 1),
('Africa', 'Africa occidentale', 'Z320', 'GNB', 'Guinea-Bissau', 'Guineense', 'GW', 'GNB', 426, 426, '624', 1),
('Africa', 'Africa occidentale', 'Z325', 'LB', 'Liberia', 'Liberiana', 'LR', 'LBR', 430, 430, '430', 1),
('Africa', 'Africa occidentale', 'Z329', 'RMM', 'Mali', 'Maliana', 'ML', 'MLI', 435, 435, '466', 1),
('Africa', 'Africa occidentale', 'Z331', 'RIM', 'Mauritania', 'Mauritana', 'MR', 'MRT', 437, 437, '478', 1),
('Africa', 'Africa occidentale', 'Z334', 'RN', 'Niger', 'Nigerina', 'NE', 'NER', 442, 442, '562', 1),
('Africa', 'Africa occidentale', 'Z335', 'WAN', 'Nigeria', 'Nigeriana', 'NG', 'NGA', 443, 443, '566', 1),
('Africa', 'Africa occidentale', 'Z343', 'SN', 'Senegal', 'Senegalese', 'SN', 'SEN', 450, 450, '686', 1),
('Africa', 'Africa occidentale', 'Z344', 'WAL', 'Sierra Leone', 'Sierraleonese', 'SL', 'SLE', 451, 451, '694', 1),
('Africa', 'Africa occidentale', 'Z351', 'TG', 'Togo', 'Togolese', 'TG', 'TGO', 458, 458, '768', 1),
('Africa', 'Africa orientale', 'Z305', 'BU', 'Burundi', 'Burundese', 'BI', 'BDI', 410, 410, '108', 1),
('Africa', 'Africa orientale', 'Z310', 'COM', 'Comore', 'Comoriana', 'KM', 'COM', 417, 417, '174', 1),
('Africa', 'Africa orientale', 'Z368', 'ER', 'Eritrea', 'Eritrea', 'ER', 'ERI', 466, 466, '232', 1),
('Africa', 'Africa orientale', 'Z315', 'ETH', 'Etiopia', 'Etiope', 'ET', 'ETH', 420, 420, '231', 1),
('Africa', 'Africa orientale', 'Z361', 'DJI', 'Gibuti', 'Gibutiana', 'DJ', 'DJI', 424, 424, '262', 1),
('Africa', 'Africa orientale', 'Z322', 'EAK', 'Kenya', 'Keniota', 'KE', 'KEN', 428, 428, '404', 1),
('Africa', 'Africa orientale', 'Z327', 'RM', 'Madagascar', 'Malgascia', 'MG', 'MDG', 432, 432, '450', 1),
('Africa', 'Africa orientale', 'Z328', 'MW', 'Malawi', 'Malawaiana', 'MW', 'MWI', 434, 434, '454', 1),
('Africa', 'Africa orientale', 'Z332', 'MS', 'Maurizio', 'Mauriziana', 'MU', 'MUS', 438, 438, '480', 1),
('Africa', 'Africa orientale', 'Z333', 'MOC', 'Mozambico', 'Mozambicana', 'MZ', 'MOZ', 440, 440, '508', 1),
('Africa', 'Africa orientale', 'Z338', 'RWA', 'Ruanda', 'Ruandese', 'RW', 'RWA', 446, 446, '646', 1),
('Africa', 'Africa orientale', 'Z342', 'SY', 'Seychelles', 'Seychellese', 'SC', 'SYC', 449, 449, '690', 1),
('Africa', 'Africa orientale', 'Z345', 'SO', 'Somalia', 'Somala', 'SO', 'SOM', 453, 453, '706', 1),
('Africa', 'Africa orientale', 'Z357', 'EAT', 'Tanzania', 'Tanzaniana', 'TZ', 'TZA', 457, 457, '834', 1),
('Africa', 'Africa orientale', 'Z353', 'EAU', 'Uganda', 'Ugandese', 'UG', 'UGA', 461, 461, '800', 1),
('Africa', 'Africa orientale', 'Z355', 'Z', 'Zambia', 'Zambiana', 'ZM', 'ZMB', 464, 464, '894', 1),
('Africa', 'Africa orientale', 'Z337', 'ZW', 'Zimbabwe', 'Zimbabwiana', 'ZW', 'ZWE', 465, 465, '716', 1),
('Africa', 'Africa settentrionale', 'Z301', 'DZ', 'Algeria', 'Algerina', 'DZ', 'DZA', 401, 401, '12', 1),
('Africa', 'Africa settentrionale', 'Z336', 'ET', 'Egitto', 'Egiziana', 'EG', 'EGY', 419, 419, '818', 1),
('Africa', 'Africa settentrionale', 'Z326', 'LAR', 'Libia', 'Libica', 'LY', 'LBY', 431, 431, '434', 1),
('Africa', 'Africa settentrionale', 'Z330', 'MA', 'Marocco', 'Marocchina', 'MA', 'MAR', 436, 436, '504', 1),
('Africa', 'Africa settentrionale', 'Z907', '907', 'Sud Sudan', 'Sudsudanese', 'SS', 'SSD', 467, 467, '728', 1),
('Africa', 'Africa settentrionale', 'Z348', 'SUN', 'Sudan', 'Sudanese', 'SD', 'SDN', 455, 455, '729', 1),
('Africa', 'Africa settentrionale', 'Z352', 'TN', 'Tunisia', 'Tunisina', 'TN', 'TUN', 460, 460, '788', 1),
('America', 'America centro meridionale', 'Z532', 'AG', 'Antigua e Barbuda', 'Antiguana, barbudana', 'AG', 'ATG', 503, 503, '28', 1),
('America', 'America centro meridionale', 'Z600', 'RA', 'Argentina', 'Argentina', 'AR', 'ARG', 602, 602, '32', 1),
('America', 'America centro meridionale', 'Z502', 'BS', 'Bahamas', 'Bahamense', 'BS', 'BHS', 505, 505, '44', 1),
('America', 'America centro meridionale', 'Z522', 'BDS', 'Barbados', 'Barbadiana', 'BB', 'BRB', 506, 506, '52', 1),
('America', 'America centro meridionale', 'Z512', 'BH', 'Belize', 'Beliziana', 'BZ', 'BLZ', 507, 507, '84', 1),
('America', 'America centro meridionale', 'Z601', 'BOL', 'Bolivia', 'Boliviana', 'BO', 'BOL', 604, 604, '68', 1),
('America', 'America centro meridionale', 'Z602', 'BR', 'Brasile', 'Brasiliana', 'BR', 'BRA', 605, 605, '76', 1),
('America', 'America centro meridionale', 'Z603', 'RCH', 'Cile', 'Cilena', 'CL', 'CHL', 606, 606, '152', 1),
('America', 'America centro meridionale', 'Z604', 'CO', 'Colombia', 'Colombiana', 'CO', 'COL', 608, 608, '170', 1),
('America', 'America centro meridionale', 'Z503', 'CR', 'Costa Rica', 'Costaricana', 'CR', 'CRI', 513, 513, '188', 1),
('America', 'America centro meridionale', 'Z504', 'C', 'Cuba', 'Cubana', 'CU', 'CUB', 514, 514, '192', 1),
('America', 'America centro meridionale', 'Z526', 'WD', 'Dominica', 'Dominicana (dominica)', 'DM', 'DMA', 515, 515, '212', 1),
('America', 'America centro meridionale', 'Z605', 'EC', 'Ecuador', 'Ecuadoregna', 'EC', 'ECU', 609, 609, '218', 1),
('America', 'America centro meridionale', 'Z506', 'ES', 'El Salvador', 'Salvadoregna', 'SV', 'SLV', 517, 517, '222', 1),
('America', 'America centro meridionale', 'Z507', 'JA', 'Giamaica', 'Giamaicana', 'JM', 'JAM', 518, 518, '388', 1),
('America', 'America centro meridionale', 'Z524', 'WG', 'Grenada', 'Grenadina', 'GD', 'GRD', 519, 519, '308', 1),
('America', 'America centro meridionale', 'Z509', 'GCA', 'Guatemala', 'Guatemalteca', 'GT', 'GTM', 523, 523, '320', 1),
('America', 'America centro meridionale', 'Z606', 'GUY', 'Guyana', 'Guyanase', 'GY', 'GUY', 612, 612, '328', 1),
('America', 'America centro meridionale', 'Z510', 'RH', 'Haiti', 'Haitiana', 'HT', 'HTI', 524, 524, '332', 1),
('America', 'America centro meridionale', 'Z511', 'HN', 'Honduras', 'Honduregna', 'HN', 'HND', 525, 525, '340', 1),
('America', 'America centro meridionale', 'Z514', 'MEX', 'Messico', 'Messicana', 'MX', 'MEX', 527, 527, '484', 1),
('America', 'America centro meridionale', 'Z515', 'NIC', 'Nicaragua', 'Nicaraguense', 'NI', 'NIC', 529, 529, '558', 1),
('America', 'America centro meridionale', 'Z516', 'PA', 'Panama', 'Panamense', 'PA', 'PAN', 530, 530, '591', 1),
('America', 'America centro meridionale', 'Z610', 'PY', 'Paraguay', 'Paraguaiana', 'PY', 'PRY', 614, 614, '600', 1),
('America', 'America centro meridionale', 'Z611', 'PE', 'Perù', 'Peruviana', 'PE', 'PER', 615, 615, '604', 1),
('America', 'America centro meridionale', 'Z505', 'DOM', 'Repubblica Dominicana', 'Dominicana (repubblica dominicana)', 'DO', 'DOM', 516, 516, '214', 1),
('America', 'America centro meridionale', 'Z533', 'KN', 'Saint Kitts e Nevis', 'Nevisiana', 'KN', 'KNA', 534, 534, '659', 1),
('America', 'America centro meridionale', 'Z528', 'WV', 'Saint Vincent e Grenadine', 'Vincentiana', 'VC', 'VCT', 533, 533, '670', 1),
('America', 'America centro meridionale', 'Z527', 'WL', 'Santa Lucia', 'Santaluciana', 'LC', 'LCA', 532, 532, '662', 1),
('America', 'America centro meridionale', 'Z608', 'SME', 'Suriname', 'Surinamese', 'SR', 'SUR', 616, 616, '740', 1),
('America', 'America centro meridionale', 'Z612', 'TT', 'Trinidad e Tobago', 'Trinidadiana', 'TT', 'TTO', 617, 617, '780', 1),
('America', 'America centro meridionale', 'Z613', 'ROU', 'Uruguay', 'Uruguaiana', 'UY', 'URY', 618, 618, '858', 1),
('America', 'America centro meridionale', 'Z614', 'YV', 'Venezuela', 'Venezuelana', 'VE', 'VEN', 619, 619, '862', 1),
('America', 'America settentrionale', 'Z401', 'CDN', 'Canada', 'Canadese', 'CA', 'CAN', 509, 509, '124', 1),
('America', 'America settentrionale', 'Z404', 'USA', 'Stati Uniti d''America', 'Statunitense', 'US', 'USA', 536, 536, '840', 1),
('Asia', 'Asia centro meridionale', 'Z200', 'AFG', 'Afghanistan', 'Afgana', 'AF', 'AFG', 301, 301, '4', 1),
('Asia', 'Asia centro meridionale', 'Z249', 'BD', 'Bangladesh', 'Bengalese', 'BD', 'BGD', 305, 305, '50', 1),
('Asia', 'Asia centro meridionale', 'Z205', 'BHT', 'Bhutan', 'Bhutanese', 'BT', 'BTN', 306, 306, '64', 1),
('Asia', 'Asia centro meridionale', 'Z222', 'IND', 'India', 'Indiana', 'IN', 'IND', 330, 330, '356', 1),
('Asia', 'Asia centro meridionale', 'Z255', 'KZ', 'Kazakhstan', 'Kazaka', 'KZ', 'KAZ', 356, 356, '398', 1),
('Asia', 'Asia centro meridionale', 'Z256', 'KS', 'Kirghizistan', 'Kirghisa', 'KG', 'KGZ', 361, 361, '417', 1),
('Asia', 'Asia centro meridionale', 'Z232', 'MV', 'Maldive', 'Maldiviana', 'MV', 'MDV', 339, 339, '462', 1),
('Asia', 'Asia centro meridionale', 'Z234', 'NEP', 'Nepal', 'Nepalese', 'NP', 'NPL', 342, 342, '524', 1),
('Asia', 'Asia centro meridionale', 'Z236', 'PK', 'Pakistan', 'Pakistana', 'PK', 'PAK', 344, 344, '586', 1),
('Asia', 'Asia centro meridionale', 'Z209', 'CL', 'Sri Lanka', 'Cingalese', 'LK', 'LKA', 311, 311, '144', 1),
('Asia', 'Asia centro meridionale', 'Z257', 'TJ', 'Tagikistan', 'Tagika', 'TJ', 'TJK', 362, 362, '762', 1),
('Asia', 'Asia centro meridionale', 'Z258', 'TM', 'Turkmenistan', 'Turkmena', 'TM', 'TKM', 364, 364, '795', 1),
('Asia', 'Asia centro meridionale', 'Z259', 'UZ', 'Uzbekistan', 'Uzbeka', 'UZ', 'UZB', 357, 357, '860', 1),
('Asia', 'Asia occidentale', 'Z203', 'KSA', 'Arabia Saudita', 'Saudita', 'SA', 'SAU', 302, 302, '682', 1),
('Asia', 'Asia occidentale', 'Z252', 'ARM', 'Armenia', 'Armena', 'AM', 'ARM', 358, 358, '51', 1),
('Asia', 'Asia occidentale', 'Z253', 'AZ', 'Azerbaigian', 'Azerbaigiana', 'AZ', 'AZE', 359, 359, '31', 1),
('Asia', 'Asia occidentale', 'Z204', 'BRN', 'Bahrein', 'Bahrayni', 'BH', 'BHR', 304, 304, '48', 1),
('Asia', 'Asia occidentale', 'Z215', 'UAE', 'Emirati Arabi Uniti', 'Emiratina', 'AE', 'ARE', 322, 322, '784', 1),
('Asia', 'Asia occidentale', 'Z254', 'GE', 'Georgia', 'Georgiana', 'GE', 'GEO', 360, 360, '268', 1),
('Asia', 'Asia occidentale', 'Z220', 'HKJ', 'Giordania', 'Giordana', 'JO', 'JOR', 327, 327, '400', 1),
('Asia', 'Asia occidentale', 'Z224', 'IR', 'Iran', 'Iraniana', 'IR', 'IRN', 332, 332, '364', 1),
('Asia', 'Asia occidentale', 'Z225', 'IRQ', 'Iraq', 'Irachena', 'IQ', 'IRQ', 333, 333, '368', 1),
('Asia', 'Asia occidentale', 'Z226', 'IL', 'Israele', 'Israeliana', 'IL', 'ISR', 334, 334, '376', 1),
('Asia', 'Asia occidentale', 'Z227', 'KWT', 'Kuwait', 'Kuwaitiana', 'KW', 'KWT', 335, 335, '414', 1),
('Asia', 'Asia occidentale', 'Z229', 'RL', 'Libano', 'Libanese', 'LB', 'LBN', 337, 337, '422', 1),
('Asia', 'Asia occidentale', 'Z235', 'OM', 'Oman', 'Omanita', 'OM', 'OMN', 343, 343, '512', 1),
('Asia', 'Asia occidentale', 'Z161', 'PN', 'Palestina', 'Palestinese (territori palestinesi)', 'PS', 'PSE', 324, 324, '275', 1),
('Asia', 'Asia occidentale', 'Z237', 'Q', 'Qatar', 'Qatariota', 'QA', 'QAT', 345, 345, '634', 1),
('Asia', 'Asia occidentale', 'Z240', 'SYR', 'Siria', 'Siriana', 'SY', 'SYR', 348, 348, '760', 1),
('Asia', 'Asia occidentale', 'Z246', 'ADN', 'Yemen', 'Yemenita', 'YE', 'YEM', 354, 354, '887', 1),
('Asia', 'Asia orientale', 'Z207', 'BRU', 'Brunei Darussalam', 'Bruneiana', 'BN', 'BRN', 309, 309, '96', 1),
('Asia', 'Asia orientale', 'Z208', 'K', 'Cambogia', 'Cambogiana', 'KH', 'KHM', 310, 310, '116', 1),
('Asia', 'Asia orientale', 'Z210', 'CN', 'Cina', 'Cinese', 'CN', 'CHN', 314, 314, '156', 1),
('Asia', 'Asia orientale', 'Z214', 'DVR', 'Corea del Nord', 'Nordcoreana', 'KP', 'PRK', 319, 319, '408', 1),
('Asia', 'Asia orientale', 'Z213', 'ROK', 'Corea del Sud', 'Sudcoreana', 'KR', 'KOR', 320, 320, '410', 1),
('Asia', 'Asia orientale', 'Z216', 'RP', 'Filippine', 'Filippina', 'PH', 'PHL', 323, 323, '608', 1),
('Asia', 'Asia orientale', 'Z219', 'J', 'Giappone', 'Giapponese', 'JP', 'JPN', 326, 326, '392', 1),
('Asia', 'Asia orientale', 'Z223', 'RI', 'Indonesia', 'Indonesiana', 'ID', 'IDN', 331, 331, '360', 1),
('Asia', 'Asia orientale', 'Z228', 'LAO', 'Laos', 'Laotiana', 'LA', 'LAO', 336, 336, '418', 1),
('Asia', 'Asia orientale', 'Z247', 'MAL', 'Malaysia', 'Malese', 'MY', 'MYS', 340, 340, '458', 1),
('Asia', 'Asia orientale', 'Z233', 'MNG', 'Mongolia', 'Mongola', 'MN', 'MNG', 341, 341, '496', 1),
('Asia', 'Asia orientale', 'Z206', 'BUR', 'Myanmar/Birmania', 'Birmana', 'MM', 'MMR', 307, 307, '104', 1),
('Asia', 'Asia orientale', 'Z248', 'SGP', 'Singapore', 'Singaporiana', 'SG', 'SGP', 346, 346, '702', 1),
('Asia', 'Asia orientale', 'Z217', 'RC', 'Taiwan', 'Taiwanese', 'TW', 'TWN', 363, 363, NULL, 1),
('Asia', 'Asia orientale', 'Z241', 'T', 'Thailandia', 'Thailandese', 'TH', 'THA', 349, 349, '764', 1),
('Asia', 'Asia orientale', 'Z242', 'TL', 'Timor Leste', 'Timorese', 'TL', 'TLS', 338, 338, '626', 1),
('Asia', 'Asia orientale', 'Z251', 'VN', 'Vietnam', 'Vietnamita', 'VN', 'VNM', 353, 353, '704', 1),
('Europa', 'Altri paesi europei', 'Z101', 'AND', 'Andorra', 'Andorrana', 'AD', 'AND', 202, 202, '20', 1),
('Europa', 'Altri paesi europei', 'Z117', 'IS', 'Islanda', 'Islandese', 'IS', 'ISL', 223, 223, '352', 1),
('Europa', 'Altri paesi europei', 'Z119', 'FL', 'Liechtenstein', 'Liechtensteinese', 'LI', 'LIE', 225, 225, '438', 1),
('Europa', 'Altri paesi europei', 'Z123', 'MC', 'Monaco', 'Monegasca', 'MC', 'MCO', 229, 229, '492', 1),
('Europa', 'Altri paesi europei', 'Z125', 'N', 'Norvegia', 'Norvegese', 'NO', 'NOR', 231, 231, '578', 1),
('Europa', 'Altri paesi europei', 'Z114', 'GB', 'Regno Unito', 'Britannica', 'UK', 'GBR', 219, 219, '826', 1),
('Europa', 'Altri paesi europei', 'Z130', 'RSM', 'San Marino', 'Sammarinese', 'SM', 'SMR', 236, 236, '674', 1),
('Europa', 'Altri paesi europei', 'Z106', 'V', 'Stato della Città del Vaticano', 'Vaticana', 'VA', 'VAT', 246, 246, '336', 1),
('Europa', 'Altri paesi europei', 'Z133', 'CH', 'Svizzera', 'Svizzera', 'CH', 'CHE', 241, 241, '756', 1),
('Europa', 'Europa centro orientale', 'Z100', 'AL', 'Albania', 'Albanese', 'AL', 'ALB', 201, 201, '8', 1),
('Europa', 'Europa centro orientale', 'Z139', 'BY', 'Bielorussia', 'Bielorussa', 'BY', 'BLR', 256, 256, '112', 1),
('Europa', 'Europa centro orientale', 'Z153', 'BIH', 'Bosnia-Erzegovina', 'Bosniaca', 'BA', 'BIH', 252, 252, '70', 1),
('Europa', 'Europa centro orientale', 'Z154', 'RUS', 'Federazione russa', 'Russa', 'RU', 'RUS', 245, 245, '643', 1),
('Europa', 'Europa centro orientale', 'Z160', 'UNK', 'Kosovo', 'Kosovara', 'XK', 'KOS', 272, 272, NULL, 1),
('Europa', 'Europa centro orientale', 'Z148', 'MK', 'Macedonia del Nord', 'Macedone', 'MK', 'MKD', 253, 253, '807', 1),
('Europa', 'Europa centro orientale', 'Z140', 'MD', 'Moldova', 'Moldava', 'MD', 'MDA', 254, 254, '498', 1),
('Europa', 'Europa centro orientale', 'Z159', 'MNE', 'Montenegro', 'Montenegrina', 'ME', 'MNE', 270, 270, '499', 1),
('Europa', 'Europa centro orientale', 'Z158', 'SRB', 'Serbia', 'Serba', 'RS', 'SRB', 271, 271, '688', 1),
('Europa', 'Europa centro orientale', 'Z243', 'TR', 'Turchia', 'Turca', 'TR', 'TUR', 351, 351, '792', 1),
('Europa', 'Europa centro orientale', 'Z138', 'UA', 'Ucraina', 'Ucraina', 'UA', 'UKR', 243, 243, '804', 1),
('Europa', 'Unione europea', 'Z102', 'A', 'Austria', 'Austriaca', 'AT', 'AUT', 203, 203, '40', 1),
('Europa', 'Unione europea', 'Z103', 'B', 'Belgio', 'Belga', 'BE', 'BEL', 206, 206, '56', 1),
('Europa', 'Unione europea', 'Z104', 'BG', 'Bulgaria', 'Bulgara', 'BG', 'BGR', 209, 209, '100', 1),
('Europa', 'Unione europea', 'Z211', 'CY', 'Cipro', 'Cipriota', 'CY', 'CYP', 315, 315, '196', 1),
('Europa', 'Unione europea', 'Z149', 'HR', 'Croazia', 'Croata', 'HR', 'HRV', 250, 250, '191', 1),
('Europa', 'Unione europea', 'Z107', 'DK', 'Danimarca', 'Danese', 'DK', 'DNK', 212, 212, '208', 1),
('Europa', 'Unione europea', 'Z144', 'EST', 'Estonia', 'Estone', 'EE', 'EST', 247, 247, '233', 1),
('Europa', 'Unione europea', 'Z109', 'FIN', 'Finlandia', 'Finlandese', 'FI', 'FIN', 214, 214, '246', 1),
('Europa', 'Unione europea', 'Z110', 'F', 'Francia', 'Francese', 'FR', 'FRA', 215, 215, '250', 1),
('Europa', 'Unione europea', 'Z112', 'D', 'Germania', 'Tedesca', 'DE', 'DEU', 216, 216, '276', 1),
('Europa', 'Unione europea', 'Z115', 'GR', 'Grecia', 'Greca', 'GR', 'GRC', 220, 220, '300', 1),
('Europa', 'Unione europea', 'Z116', 'IRL', 'Irlanda', 'Irlandese', 'IE', 'IRL', 221, 221, '372', 1),
('Europa', 'Unione europea', '', 'IT', 'Italia', 'Italiana', 'IT', 'ITA', 100, 100, '380', 1),
('Europa', 'Unione europea', 'Z145', 'LV', 'Lettonia', 'Lettone', 'LV', 'LVA', 248, 248, '428', 1),
('Europa', 'Unione europea', 'Z146', 'LT', 'Lituania', 'Lituana', 'LT', 'LTU', 249, 249, '440', 1),
('Europa', 'Unione europea', 'Z120', 'L', 'Lussemburgo', 'Lussemburghese', 'LU', 'LUX', 226, 226, '442', 1),
('Europa', 'Unione europea', 'Z121', 'M', 'Malta', 'Maltese', 'MT', 'MLT', 227, 227, '470', 1),
('Europa', 'Unione europea', 'Z126', 'NL', 'Paesi Bassi', 'Olandese', 'NL', 'NLD', 232, 232, '528', 1),
('Europa', 'Unione europea', 'Z127', 'PL', 'Polonia', 'Polacca', 'PL', 'POL', 233, 233, '616', 1),
('Europa', 'Unione europea', 'Z128', 'P', 'Portogallo', 'Portoghese', 'PT', 'PRT', 234, 234, '620', 1),
('Europa', 'Unione europea', 'Z156', 'CZ', 'Repubblica ceca', 'Ceca', 'CZ', 'CZE', 257, 257, '203', 1),
('Europa', 'Unione europea', 'Z129', 'RO', 'Romania', 'Romena', 'RO', 'ROU', 235, 235, '642', 1),
('Europa', 'Unione europea', 'Z155', 'SK', 'Slovacchia', 'Slovacca', 'SK', 'SVK', 255, 255, '703', 1),
('Europa', 'Unione europea', 'Z150', 'SLO', 'Slovenia', 'Slovena', 'SI', 'SVN', 251, 251, '705', 1),
('Europa', 'Unione europea', 'Z131', 'E', 'Spagna', 'Spagnola', 'ES', 'ESP', 239, 239, '724', 1),
('Europa', 'Unione europea', 'Z132', 'S', 'Svezia', 'Svedese', 'SE', 'SWE', 240, 240, '752', 1),
('Europa', 'Unione europea', 'Z134', 'H', 'Ungheria', 'Ungherese', 'HU', 'HUN', 244, 244, '348', 1),
('Oceania', 'Oceania', 'Z700', 'AUS', 'Australia', 'Australiana', 'AU', 'AUS', 701, 701, '36', 1),
('Oceania', 'Oceania', 'Z704', 'FJI', 'Figi', 'Figiana', 'FJ', 'FJI', 703, 703, '242', 1),
('Oceania', 'Oceania', 'Z711', 'MH', 'Isole Marshall', 'Marshall', 'MH', 'MHL', 712, 712, '584', 1),
('Oceania', 'Oceania', 'Z724', 'SLB', 'Isole Salomone', 'Salomone', 'SB', 'SLB', 725, 725, '90', 1),
('Oceania', 'Oceania', 'Z731', 'KIR', 'Kiribati', 'Gilbertese', 'KI', 'KIR', 708, 708, '296', 1),
('Oceania', 'Oceania', 'Z713', 'NAU', 'Nauru', 'Nauruana', 'NR', 'NRU', 715, 715, '520', 1),
('Oceania', 'Oceania', 'Z719', 'NZ', 'Nuova Zelanda', 'Neozelandese', 'NZ', 'NZL', 719, 719, '554', 1),
('Oceania', 'Oceania', 'Z734', 'PAL', 'Palau', 'Palauana', 'PW', 'PLW', 720, 720, '585', 1),
('Oceania', 'Oceania', 'Z730', 'PNG', 'Papua Nuova Guinea', 'Guineana (papua nuova guinea)', 'PG', 'PNG', 721, 721, '598', 1),
('Oceania', 'Oceania', 'Z726', 'WS', 'Samoa', 'Samoana', 'WS', 'WSM', 727, 727, '882', 1),
('Oceania', 'Oceania', 'Z735', 'FSM', 'Stati Federati di Micronesia', 'Micronesiana', 'FM', 'FSM', 713, 713, '583', 1),
('Oceania', 'Oceania', 'Z728', 'TO', 'Tonga', 'Tongana', 'TO', 'TON', 730, 730, '776', 1),
('Oceania', 'Oceania', 'Z732', 'TUV', 'Tuvalu', 'Tuvaluana', 'TV', 'TUV', 731, 731, '798', 1),
('Oceania', 'Oceania', 'Z733', 'VU', 'Vanuatu', 'Vanuatuana', 'VU', 'VUT', 732, 732, '548', 1),
(NULL, NULL, 'Z529', 'AIA', 'Anguilla (isola)', 'Anguillana', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z500', '500', 'Antille britanniche', 'Antillana (antille britanniche)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z521', '521', 'Antille britanniche', 'Antillana (antille britanniche)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z523', '523', 'Antille britanniche', 'Antillana (antille britanniche)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z501', 'ANT', 'Antille olandesi', 'Antillana (antille olandesi)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z201', '201', 'Arabia meridionale federazione', 'Yemenita (federazione dell''arabia meridionale)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z202', '202', 'Arabia meridionale protettorato', 'Yemenita (protettorato dell''arabia meridionale)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z137', '137', 'Armenia', 'Armena', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z141', '141', 'Azerbaidjan', 'Azerbaigiana', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z303', '303', 'Basutoland sud africa britann', 'Lesothiana (basutoland-sud africa britannico)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z304', '304', 'Beciuania sud africa britannico', 'Beciuana', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z400', 'BMU', 'Bermuda (isole)', 'Bermudiana', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z364', '364', 'Bophuthatswana', 'Batswana', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z701', '701', 'Caroline (isole)', 'Micronesiana (isole caroline)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z530', 'CYM', 'Cayman (isole)', 'Caymaniana', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z105', 'CS', 'Cecoslovacchia', 'Ceca (cecoslovacchia)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z702', 'CXR', 'Christmas (isola)', 'Christmas (isola)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z367', '367', 'Ciskei', 'Centraficana (ciskei)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z212', 'CCK', 'Cocos (isole)', 'Cocos (isole)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z370', 'CB', 'Congo belga', 'Congolese (congo belga)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z703', 'COK', 'Cook (isole)', 'Cookese', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z900', '900', 'Dipendenze australiane', 'Australiana (dipendenze australiane)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z901', '901', 'Dipendenze britanniche', 'Britannica (dipendenze britanniche)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z800', '800', 'Dipendenze canadesi', 'Canadese (dipendenze canadesi)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z902', '902', 'Dipendenze francesi', 'Francese (dipendenze francesi)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z903', '903', 'Dipendenze neozelandesi', 'Neozelandese (dipendenze neozelandesi)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z904', '904', 'Dipendenze norvegesi antartiche', 'Norvegese (dipendenze norvegesi antartiche)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z801', '801', 'Dipendenze norvegesi artiche', 'Norvegese (dipendenze norvegesi artiche)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z802', '802', 'Dipendenze sovietiche', 'Russa (dipendenze russe)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z905', '905', 'Dipendenze statunitensi', 'Statunitense (dipendenze statunitensi)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z906', '906', 'Dipendenze sudafricane', 'Sudafricana (dipendenze sudafricane)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z108', 'FO', 'Faer oer (isole)', 'Faroese', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z218', '218', 'Gaza (territorio di)', 'Palestinese (territorio di gaza)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z136', '136', 'Georgia', 'Georgiana', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z111', 'DDR', 'Germania repubblica democratica', 'Tedesca (repubblica democratica tedesca)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z113', 'GBZ', 'Gibilterra', 'Gibilterrina', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z705', '705', 'Gilbert e ellice (isole)', 'Centraficana (isole gilbert e ellice)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z402', 'GRL', 'Groenlandia', 'Groenlandese', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z508', 'GP', 'Guadalupa', 'Guadalupeense', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z706', 'GUM', 'Guam (isola)', 'Guamaniane', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z607', 'GF', 'Guyana=guiana francese', 'Guyanase (guayana=guiana francese)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z221', 'HK', 'Hong kong', 'Hongkonghese', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z323', '323', 'Ifni', 'Marocchina (ifni)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z707', '707', 'Irian occidentale', 'Papuana', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z721', '721', 'Isole cilene (pasqua e sala y gomez)', 'Isole cilene (pasqua e sala y gomez)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z118', 'YU', 'Jugoslavia', 'Iugoslava', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z152', '152', 'Kazakhistan', 'Kazaka', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z142', '142', 'Kirghizistan', 'Kirghisa', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z324', 'REU', 'La reunion (isola)', 'Reunionese', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z231', 'MAC', 'Macao', 'Macao', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z708', '708', 'Macquarie (isole)', 'Macquarie (isole)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z230', 'MY', 'Malaysia', 'Malese', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z609', 'FLK', 'Malvine=falkland (isole)', 'Malviniana', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z122', '122', 'Man', 'Mannese', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z709', '709', 'Marcus (isole)', 'Giapponese (isole marcus)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z710', 'MNP', 'Marianne (isole)', 'Marianne (isole)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z513', 'MQ', 'Martinica', 'Martinicana', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z360', 'MYT', 'Mayotte (isola)', 'Francese (isola mayotte)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z712', '712', 'Midway (isole)', 'Midway (isole)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z531', 'MSR', 'Montserrat', 'Montserratiana', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z714', 'NIU', 'Niue=savage (isole)', 'Niueana', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z715', 'NFK', 'Norfolk (isole e isole del mar dei coral', 'Norfolk (isole e isole del mar dei coralli)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z124', '124', 'Normanne isole isole del canale', 'Normanne isole isole del canale', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z716', 'NCL', 'Nuova caledonia (isole e dipendenze)', 'Caledoniana', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z718', 'PG.', 'Nuova guinea', 'Guineana (nuova guinea)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z717', 'NHE', 'Nuove ebridi (isole condominio franco-in', 'Nuove ebridi (isole condominio franco-inglese)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z369', '369', 'Nyasaland', 'Malawiana', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z517', '517', 'Panama zona del canale', 'Panamense (panama zona del canale)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z720', 'PG', 'Papuasia', 'Guineana (papuasia)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z722', 'PCN', 'Pitcairn (e dipendenze)', 'Pitcairn (e dipendenze)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z723', 'PYF', 'Polinesia francese (isole)', 'Polinesiana', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z518', 'PRI', 'Puerto rico', 'Portoricana', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z238', '238', 'Ryukyu (isole)', 'Giapponese (isole ryukyu)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z362', '362', 'Sahara meridionale', 'Sahariana (sahara meridionale)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z363', '363', 'Sahara settentrionale', 'Sahariana (sahara settentrionale)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z339', '339', 'Sahara spagnolo', 'Sahariana (sahara spagnolo)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z403', 'SPM', 'Saint pierre et miquelon (isole)', 'Francese (isole saint pierre et miquelon)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z725', 'ASM', 'Samoa americane (isole)', 'Samoana americana', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z340', 'SHN', 'Sant''elena (isola)', 'Santeleniana', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z157', 'SCG', 'Serbia e montenegro', 'Serba (serbia e montenegro)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z239', '239', 'Sikkim', 'Sikkim', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z346', 'CFS', 'Somalia francese', 'Territorio francese degli afar e degli issa', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z147', '147', 'Tagikistan', 'Tagika', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z350', '350', 'Tanganica', 'Tanzaniana (tanganica)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z727', 'TKL', 'Tokelau isole dell''unione', 'Tonganiana', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z365', '365', 'Transkei', 'Transkei', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z151', '151', 'Turkmenistan', 'Turkmena', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z519', 'TCA', 'Turks e caicos (isole)', 'Turks e caicos (isole)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z135', 'SU', 'Unione repubbliche socialiste sovietiche', 'Sovietica', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z143', '143', 'Uzbekistan', 'Uzbeka', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z366', '366', 'Venda', 'Venda', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z520', 'VIR', 'Vergini americane (isole)', 'Statunitense (isole vergini americane)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z525', 'BVI', 'Vergini britanniche (isole)', 'Britannica (isole vergini britanniche)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z245', 'VNN', 'Vietnam del nord', 'Nordvietnamita', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z244', 'VNS', 'Vietnam del sud', 'Sudvietnamita', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z729', 'WLF', 'Wallis e futuna (isole)', 'Wallis e futuna (isole)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z250', 'YS', 'Yemen rep. dem. popolare', 'Yemenita (repubblica democratica popolare dello yemen)', NULL, NULL, NULL, NULL, NULL, 0),
(NULL, NULL, 'Z356', '356', 'Zanzibar', 'Tanzaniana (zanzibar)', NULL, NULL, NULL, NULL, NULL, 0);
-- UNLOCK TABLES;
